In [13]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

import pandas as pd 
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [2]:
df = pd.read_csv('bias_and_DAIRYance/unzipped_data/Train.csv')

df.columns.values

/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2705: DtypeWarning: Columns (13,39,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

array(['SalesID', 'SalePrice', 'MachineID', 'ModelID', 'datasource',
       'auctioneerID', 'YearMade', 'MachineHoursCurrentMeter', 'UsageBand',
       'saledate', 'fiModelDesc', 'fiBaseModel', 'fiSecondaryDesc',
       'fiModelSeries', 'fiModelDescriptor', 'ProductSize',
       'fiProductClassDesc', 'state', 'ProductGroup', 'ProductGroupDesc',
       'Drive_System', 'Enclosure', 'Forks', 'Pad_Type', 'Ride_Control',
       'Stick', 'Transmission', 'Turbocharged', 'Blade_Extension',
       'Blade_Width', 'Enclosure_Type', 'Engine_Horsepower', 'Hydraulics',
       'Pushblock', 'Ripper', 'Scarifier', 'Tip_Control', 'Tire_Size',
       'Coupler', 'Coupler_System', 'Grouser_Tracks', 'Hydraulics_Flow',
       'Track_Type', 'Undercarriage_Pad_Width', 'Stick_Length', 'Thumb',
       'Pattern_Changer', 'Grouser_Type', 'Backhoe_Mounting', 'Blade_Type',
       'Travel_Controls', 'Differential_Type', 'Steering_Controls'], dtype=object)

In [3]:
df['ProductGroupDesc'].unique()

array(['Wheel Loader', 'Skid Steer Loaders', 'Track Excavators',
       'Backhoe Loaders', 'Track Type Tractors', 'Motor Graders'], dtype=object)

In [5]:
df.groupby('ProductGroupDesc').count()

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,...,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
ProductGroupDesc,,,,,,,,,,,,,,,,,,,,,
Backhoe Loaders,79415,79415,79415,79415,79415,74718,79415,26389,12507,79415,...,0,0,0,0,0,0,0,0,0,0
Motor Graders,25489,25489,25489,25489,25489,24395,25489,8901,2780,25489,...,0,0,0,0,0,0,0,0,0,0
Skid Steer Loaders,43488,43488,43488,43488,43488,41718,43488,16810,10762,43488,...,0,0,0,0,0,0,0,0,0,0
Track Excavators,101167,101167,101167,101167,101167,95116,101167,36308,19892,101167,...,99872,99218,99288,99218,99153,0,0,0,0,0
Track Type Tractors,80520,80520,80520,80520,80520,76710,80520,28841,12854,80520,...,0,0,0,0,0,78672,79833,79834,0,0
Wheel Loader,71046,71046,71046,71046,71046,68332,71046,25516,10844,71046,...,0,0,0,0,0,0,0,0,69411,69369

In [8]:
df['ProductGroupDesc'].unique()

array(['Wheel Loader', 'Skid Steer Loaders', 'Track Excavators',
       'Backhoe Loaders', 'Track Type Tractors', 'Motor Graders'], dtype=object)

In [9]:
pd.get_dummies(df['ProductGroup']).drop('TEX', axis=1)

        BL  MG  SSL  TTT  WL
0        0   0    0    0   1
1        0   0    0    0   1
2        0   0    1    0   0
3        0   0    0    0   0
4        0   0    1    0   0
5        1   0    0    0   0
6        0   0    0    0   0
7        1   0    0    0   0
8        0   0    0    0   0
9        0   0    0    0   1
10       1   0    0    0   0
11       0   0    0    1   0
12       0   0    0    0   0
13       1   0    0    0   0
14       1   0    0    0   0
15       1   0    0    0   0
16       0   0    0    0   0
17       0   0    0    0   0
18       0   0    0    0   0
19       1   0    0    0   0
20       0   0    0    0   0
21       0   1    0    0   0
22       0   0    0    0   0
23       0   0    0    0   1
24       1   0    0    0   0
25       0   0    1    0   0
26       0   0    0    0   0
27       0   0    0    0   0
28       0   1    0    0   0
29       0   0    0    0   0
...     ..  ..  ...  ...  ..
401095   0   0    0    0   0
401096   0   0    0    0   0
401097   0   0    0    0   0
401098   0   0    0    0   0
401099   0   0    0    0   0
401100   0   0    0    0   0
401101   0   0    0    0   0
401102   0   0    0    0   0
401103   0   0    0    0   0
401104   0   0    0    0   0
401105   0   0    0    0   0
401106   0   0    0    0   0
401107   0   0    0    0   0
401108   0   0    0    0   0
401109   0   0    0    0   0
401110   0   0    0    0   0
401111   0   0    0    0   0
401112   0   0    0    0   0
401113   0   0    0    0   0
401114   0   0    0    0   0
401115   0   0    0    0   0
401116   0   0    0    0   0
401117   0   0    0    0   0
401118   0   0    0    0   0
401119   0   0    0    0   0
401120   0   0    0    0   0
401121   0   0    0    0   0
401122   0   0    0    0   0
401123   0   0    0    0   0
401124   0   0    0    0   0

[401125 rows x 5 columns]

In [10]:
print df['ProductGroup'].unique()
print df['ProductGroupDesc'].unique()
df.drop('TEX')

['WL' 'SSL' 'TEX' 'BL' 'TTT' 'MG']
['Wheel Loader' 'Skid Steer Loaders' 'Track Excavators' 'Backhoe Loaders'
 'Track Type Tractors' 'Motor Graders']

ValueError: labels ['TEX'] not contained in axis

In [11]:
prod_groups = pd.get_dummies(tract['ProductGroup']).drop('TEX', axis=1)
df = pd.concat([df, prod_groups], axis=1)

NameError: name 'tract' is not defined

In [78]:



#creates categorical values for 6 different product groups
#sets baseline of variable 'TEX' as our most frequently sold type
prod_groups = pd.get_dummies(df['ProductGroup']).drop('TEX', axis=1)
#adds variables to end of dataframe
df1 = pd.concat([df, prod_groups], axis=1)


y_train = df1['SalePrice']
X_train = df1[['WL','SSL','BL','TTT','MG']]

X_train = sm.add_constant(X_train)
model = sm.OLS(y_train, X_train)
result = model.fit()
print result.summary()

                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.188
Model:                            OLS   Adj. R-squared:                  0.188
Method:                 Least Squares   F-statistic:                 1.854e+04
Date:                Fri, 09 Dec 2016   Prob (F-statistic):               0.00
Time:                        13:55:40   Log-Likelihood:            -4.5567e+06
No. Observations:              401125   AIC:                         9.113e+06
Df Residuals:                  401119   BIC:                         9.113e+06
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const       3.567e+04     65.276    546.394      0.000      3.55e+04  3.58e+04
WL          1386.3426    101.628     13.641      0.000      1187.155  1585.530
SSL        -2.512e+04    119.051   -210.974      0.000     -2.53e+04 -2.49e+04
BL         -1.477e+04     98.432   -150.040      0.000      -1.5e+04 -1.46e+04
TTT          492.2916     98.053      5.021      0.000       300.111   684.472
MG          1.159e+04    145.508     79.621      0.000      1.13e+04  1.19e+04
==============================================================================
Omnibus:                    85608.964   Durbin-Watson:                   0.670
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           180932.905
Skew:                           1.254   Prob(JB):                         0.00
Kurtosis:                       5.129   Cond. No.                         5.99
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [57]:
testdf = pd.read_csv('./bias_and_DAIRYance/unzipped_data/test.csv')

In [74]:
#creates categorical values for 6 different product groups
#sets baseline of variable 'TEX' as our most frequently sold type
prod_groups = pd.get_dummies(testdf['ProductGroup']).drop('TEX', axis=1)
#adds variables to end of dataframe
df2 = pd.concat([testdf, prod_groups], axis=1)

cols = ['WL','SSL','BL','TTT','MG']
xtest = sm.add_constant(df2[cols])

In [63]:
print xtest.head()
print X_train.head()

   const  WL  SSL  BL  TTT  MG
0      1   0    0   0    0   0
1      1   0    0   0    0   0
2      1   0    0   0    0   0
3      1   0    0   0    0   0
4      1   1    0   0    0   0
   const  WL  SSL  BL  TTT  MG
0      1   1    0   0    0   0
1      1   1    0   0    0   0
2      1   0    1   0    0   0
3      1   0    0   0    0   0
4      1   0    1   0    0   0

In [82]:
result.predict(xtest)

array([ 35666.12062233,  35666.12062233,  35666.12062233, ...,
        35666.12062233,  35666.12062233,  35666.12062233])

In [69]:
testdf['SalePrice'] = result.predict(xtest)

In [72]:
testdf[['SalesID', 'SalePrice']].to_csv('out.csv', index=False, sep=',')